package com.google.assistant.plugin.appactions.xml.actions.els;

import com.intellij.util.xml.NamedEnum;
import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;

/* compiled from: IntentName.kt */
@Metadata(mv = {1, 4, 2}, bv = {1, 0, 3}, k = 1, d1 = {"��\u0016\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0018\u0002\n��\n\u0002\u0010\u000e\n\u0002\b@\b\u0086\u0001\u0018��2\b\u0012\u0004\u0012\u00020��0\u00012\u00020\u0002B\u000f\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0004¢\u0006\u0002\u0010\u0005J\b\u0010\u0006\u001a\u00020\u0004H\u0016R\u000e\u0010\u0003\u001a\u00020\u0004X\u0082\u0004¢\u0006\u0002\n��j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bC¨\u0006D"}, d2 = {"Lcom/google/assistant/plugin/appactions/xml/actions/els/IntentName;", "", "Lcom/intellij/util/xml/NamedEnum;", "value", "", "(Ljava/lang/String;ILjava/lang/String;)V", "getValue", "ACTIONS_INTENT_CREATE_CALL", "ACTIONS_INTENT_CREATE_REVIEW", "ACTIONS_INTENT_CREATE_CONTACT_POINT", "ACTIONS_INTENT_CREATE_MESSAGE", "ACTIONS_INTENT_CREATE_MONEY_TRANSFER", "ACTIONS_INTENT_CREATE_TAXI_RESERVATION", "ACTIONS_INTENT_CREATE_TRADE_ORDER", "ACTIONS_INTENT_GET_ACCOUNT", "ACTIONS_INTENT_GET_THING", "ACTIONS_INTENT_OPEN_APP_FEATURE", "ACTIONS_INTENT_PAUSE_EXERCISE", "ACTIONS_INTENT_RECORD_FOOD_OBSERVATION", "ACTIONS_INTENT_PAY_INVOICE", "ACTIONS_INTENT_GET_BARCODE", "ACTIONS_INTENT_GET_NEWS_ARTICLE", "ACTIONS_INTENT_GET_REVIEW", "ACTIONS_INTENT_GET_SERVICE_OBSERVATION", "ACTIONS_INTENT_UPDATE_ACCOUNT", "ACTIONS_INTENT_UPDATE_SOFTWARE_APPLICATION", "ACTIONS_INTENT_UPDATE_GET_ACCOUNT", "ACTIONS_INTENT_GET_MESSAGE", "ACTIONS_INTENT_GET_FINANCIAL_POSITION", "ACTIONS_INTENT_GET_INVOICE", "ACTIONS_INTENT_GET_STOCK_QUOTE", "ACTIONS_INTENT_ORDER_MENU_ITEM", "ACTIONS_INTENT_START_GAME_EVENT", "ACTIONS_INTENT_GET_GAME_OBSERVATION", "ACTIONS_INTENT_GET_EXERCISE_OBSERVATION", "ACTIONS_INTENT_GET_EXERCISE_PLAN", "ACTIONS_INTENT_GET_FOOD_OBSERVATION", "ACTIONS_INTENT_GET_HEALTH_OBSERVATION", "ACTIONS_INTENT_RECORD_EXERCISE", "ACTIONS_INTENT_RECORD_HEALTH_OBSERVATION", "ACTIONS_INTENT_RESUME_EXERCISE", "ACTIONS_INTENT_START_EXERCISE", "ACTIONS_INTENT_STOP_EXERCISE", "ACTIONS_INTENT_CREATE_ITEM_LIST", "ACTIONS_INTENT_GET_DIGITAL_DOCUMENT", "ACTIONS_INTENT_GET_ITEM_LIST", "ACTIONS_INTENT_CREATE_DIGITAL_DOCUMENT", "ACTIONS_INTENT_UPDATE_DIGITAL_DOCUMENT", "ACTIONS_INTENT_UPDATE_ITEM_LIST", "ACTIONS_INTENT_CREATE_OFFER", "ACTIONS_INTENT_CREATE_ORDER", "ACTIONS_INTENT_GET_CART", "ACTIONS_INTENT_GET_PRODUCT", "ACTIONS_INTENT_UPDATE_CART", "ACTIONS_INTENT_CREATE_MEDIA_OBJECT", "ACTIONS_INTENT_CREATE_PHOTOGRAPH", "ACTIONS_INTENT_CREATE_SOCIAL_MEDIA_CONNECTION", "ACTIONS_INTENT_CREATE_SOCIAL_MEDIA_POSTING", "ACTIONS_INTENT_GET_IMAGE_OBJECT", "ACTIONS_INTENT_GET_SOCIAL_MEDIA_POSTING", "ACTIONS_INTENT_GET_SOCIAL_MEDIA_PROFILE", "ACTIONS_INTENT_CANCEL_TAXI_RESERVATION", "ACTIONS_INTENT_GET_TAXI_RESERVATION", "ACTIONS_INTENT_CREATE_FLIGHT_RESERVATION", "ACTIONS_INTENT_CREATE_LODGING_RESERVATION", "ACTIONS_INTENT_GET_LOCAL_BUSINESS", "ACTIONS_INTENT_UPDATE_RESERVATION", "ACTIONS_INTENT_CREATE_THING", "app-actions-test-tool-kotlin"})
/* loaded from: google-assistant-plugin-2.5.1.zip:google-assistant-plugin/lib/app-actions-test-tool-kotlin-2.5.1.jar:com/google/assistant/plugin/appactions/xml/actions/els/IntentName.class */
public enum IntentName implements NamedEnum {
    ACTIONS_INTENT_CREATE_CALL("actions.intent.CREATE_CALL"),
    ACTIONS_INTENT_CREATE_REVIEW("actions.intent.CREATE_REVIEW"),
    ACTIONS_INTENT_CREATE_CONTACT_POINT("actions.intent.CREATE_CONTACT_POINT"),
    ACTIONS_INTENT_CREATE_MESSAGE("actions.intent.CREATE_MESSAGE"),
    ACTIONS_INTENT_CREATE_MONEY_TRANSFER("actions.intent.CREATE_MONEY_TRANSFER"),
    ACTIONS_INTENT_CREATE_TAXI_RESERVATION("actions.intent.CREATE_TAXI_RESERVATION"),
    ACTIONS_INTENT_CREATE_TRADE_ORDER("actions.intent.CREATE_TRADE_ORDER"),
    ACTIONS_INTENT_GET_ACCOUNT("actions.intent.GET_ACCOUNT"),
    ACTIONS_INTENT_GET_THING("actions.intent.GET_THING"),
    ACTIONS_INTENT_OPEN_APP_FEATURE("actions.intent.OPEN_APP_FEATURE"),
    ACTIONS_INTENT_PAUSE_EXERCISE("actions.intent.PAUSE_EXERCISE"),
    ACTIONS_INTENT_RECORD_FOOD_OBSERVATION("actions.intent.RECORD_FOOD_OBSERVATION"),
    ACTIONS_INTENT_PAY_INVOICE("actions.intent.PAY_INVOICE"),
    ACTIONS_INTENT_GET_BARCODE("actions.intent.GET_BARCODE"),
    ACTIONS_INTENT_GET_NEWS_ARTICLE("actions.intent.GET_NEWS_ARTICLE"),
    ACTIONS_INTENT_GET_REVIEW("actions.intent.GET_REVIEW"),
    ACTIONS_INTENT_GET_SERVICE_OBSERVATION("actions.intent.GET_SERVICE_OBSERVATION"),
    ACTIONS_INTENT_UPDATE_ACCOUNT("actions.intent.UPDATE_ACCOUNT"),
    ACTIONS_INTENT_UPDATE_SOFTWARE_APPLICATION("actions.intent.UPDATE_SOFTWARE_APPLICATION"),
    ACTIONS_INTENT_UPDATE_GET_ACCOUNT("actions.intent.GET_ACCOUNT"),
    ACTIONS_INTENT_GET_MESSAGE("actions.intent.GET_MESSAGE"),
    ACTIONS_INTENT_GET_FINANCIAL_POSITION("actions.intent.GET_FINANCIAL_POSITION"),
    ACTIONS_INTENT_GET_INVOICE("actions.intent.GET_INVOICE"),
    ACTIONS_INTENT_GET_STOCK_QUOTE("actions.intent.GET_STOCK_QUOTE"),
    ACTIONS_INTENT_ORDER_MENU_ITEM("actions.intent.ORDER_MENU_ITEM"),
    ACTIONS_INTENT_START_GAME_EVENT("actions.intent.START_GAME_EVENT"),
    ACTIONS_INTENT_GET_GAME_OBSERVATION("actions.intent.GET_GAME_OBSERVATION"),
    ACTIONS_INTENT_GET_EXERCISE_OBSERVATION("actions.intent.GET_EXERCISE_OBSERVATION"),
    ACTIONS_INTENT_GET_EXERCISE_PLAN("actions.intent.GET_EXERCISE_PLAN"),
    ACTIONS_INTENT_GET_FOOD_OBSERVATION("actions.intent.GET_FOOD_OBSERVATION"),
    ACTIONS_INTENT_GET_HEALTH_OBSERVATION("actions.intent.GET_HEALTH_OBSERVATION"),
    ACTIONS_INTENT_RECORD_EXERCISE("actions.intent.RECORD_EXERCISE"),
    ACTIONS_INTENT_RECORD_HEALTH_OBSERVATION("actions.intent.RECORD_HEALTH_OBSERVATION"),
    ACTIONS_INTENT_RESUME_EXERCISE("actions.intent.RESUME_EXERCISE"),
    ACTIONS_INTENT_START_EXERCISE("actions.intent.START_EXERCISE"),
    ACTIONS_INTENT_STOP_EXERCISE("actions.intent.STOP_EXERCISE"),
    ACTIONS_INTENT_CREATE_ITEM_LIST("actions.intent.CREATE_ITEM_LIST"),
    ACTIONS_INTENT_GET_DIGITAL_DOCUMENT("actions.intent.GET_DIGITAL_DOCUMENT"),
    ACTIONS_INTENT_GET_ITEM_LIST("actions.intent.GET_ITEM_LIST"),
    ACTIONS_INTENT_CREATE_DIGITAL_DOCUMENT("actions.intent.CREATE_DIGITAL_DOCUMENT"),
    ACTIONS_INTENT_UPDATE_DIGITAL_DOCUMENT("actions.intent.UPDATE_DIGITAL_DOCUMENT"),
    ACTIONS_INTENT_UPDATE_ITEM_LIST("actions.intent.UPDATE_ITEM_LIST"),
    ACTIONS_INTENT_CREATE_OFFER("actions.intent.CREATE_OFFER"),
    ACTIONS_INTENT_CREATE_ORDER("actions.intent.CREATE_ORDER"),
    ACTIONS_INTENT_GET_CART("actions.intent.GET_CART"),
    ACTIONS_INTENT_GET_PRODUCT("actions.intent.GET_PRODUCT"),
    ACTIONS_INTENT_UPDATE_CART("actions.intent.UPDATE_CART"),
    ACTIONS_INTENT_CREATE_MEDIA_OBJECT("actions.intent.CREATE_MEDIA_OBJECT"),
    ACTIONS_INTENT_CREATE_PHOTOGRAPH("actions.intent.CREATE_PHOTOGRAPH"),
    ACTIONS_INTENT_CREATE_SOCIAL_MEDIA_CONNECTION("actions.intent.CREATE_SOCIAL_MEDIA_CONNECTION"),
    ACTIONS_INTENT_CREATE_SOCIAL_MEDIA_POSTING("actions.intent.CREATE_SOCIAL_MEDIA_POSTING"),
    ACTIONS_INTENT_GET_IMAGE_OBJECT("actions.intent.GET_IMAGE_OBJECT"),
    ACTIONS_INTENT_GET_SOCIAL_MEDIA_POSTING("actions.intent.GET_SOCIAL_MEDIA_POSTING"),
    ACTIONS_INTENT_GET_SOCIAL_MEDIA_PROFILE("actions.intent.GET_SOCIAL_MEDIA_PROFILE"),
    ACTIONS_INTENT_CANCEL_TAXI_RESERVATION("actions.intent.CANCEL_TAXI_RESERVATION"),
    ACTIONS_INTENT_GET_TAXI_RESERVATION("actions.intent.GET_TAXI_RESERVATION"),
    ACTIONS_INTENT_CREATE_FLIGHT_RESERVATION("actions.intent.CREATE_FLIGHT_RESERVATION"),
    ACTIONS_INTENT_CREATE_LODGING_RESERVATION("actions.intent.CREATE_LODGING_RESERVATION"),
    ACTIONS_INTENT_GET_LOCAL_BUSINESS("actions.intent.GET_LOCAL_BUSINESS"),
    ACTIONS_INTENT_UPDATE_RESERVATION("actions.intent.UPDATE_RESERVATION"),
    ACTIONS_INTENT_CREATE_THING("actions.intent.CREATE_THING");
    
    private final String value;

    IntentName(String value) {
        this.value = value;
    }

    @NotNull
    public String getValue() {
        return this.value;
    }
}
